name = "CodecZlibNG"
uuid = "642d12eb-acb5-4437-bcfc-a25e07ad685c"
license = "MIT"
authors = ["Tomas Drvostep <tomas.drvostep@gmail.com>", "Kenta Sato <bicycle1885@gmail.com>"]
version = "0.1.0"

[deps]
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"
ZlibNG_jll = "c62bbaca-5768-5b75-85e2-9a0ea54e1624"

[compat]
TranscodingStreams = "0.9"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
